"""Add add column User_id

Revision ID: f8d5469d79f3
Revises: 96019c81396a
Create Date: 2024-09-20 20:22:05.784026

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8d5469d79f3"
down_revision: Union[str, None] = "96019c81396a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_note_user_id_user"), "note", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_note_user_id_user"), "note", type_="foreignkey")
    op.drop_column("note", "user_id")
    # ### end Alembic commands ###
